version: '24.0'

services:
    database:
      image: postgres
      environment:
        - POSTGRES_DB=powefit
        - POSTGRES_USER=admin1726
        - POSTGRES_PASSWORD=p0w3rf1t.20*
      ports:
        - '5432:5432'
      volumes:
        - ./postgres_data:/var/lib/postgresql
